export const REQUEST_CAMERAS = 'REQUEST_CAMERAS'
export const RECEIVE_CAMERAS = 'RECEIVE_CAMERAS'
export const CAMERAS_ERROR = 'CAMERAS_ERROR'

export const ADD_FAVORITE = 'ADD_FAVORITE'
export const ADD_FAVORITES = 'ADD_FAVORITES'
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE'
